### PR TITLE
Type definitions were added

### PR DESCRIPTION
**Pull request by muturgan**

### CODE REVIEW

**Comment by simonlc** [comment]
Thank you for your contribution. I'm not very knowledgeable of typescript, so I might not be the best to review this. I did notice however that you can pass either a number or string for the mode, e.g., `mkdirp('/test/thing', '777')` but this doesn't seem to be reflected in the latest documentation.

My other concern is the /// directive seems to be referencing a package? Should that be listed as a peer dep, or is it automatically included by typescript?

I should also mention I should be deprecating this package as node 10.12 does support the recursive option. I will update the readme with information on how to use it for people who might stumble upon the package.

**Comment by muturgan** [comment]
Hello!

Thank you for your observation. Indeed, the "mode" parameter supports types other than number. I will fix it.

About /// directive. It means something like "our d.ts file extands @types/node package". It would be correct to specify it in the devDependencies field. But I didn't because:
1) I wasn't sure which version of @types/node to specify;
2) Everyone who using typescript with node.js must install @types/node and I was sure that the necessary dependence will be installed in any case.

Based on what you said about node 10.12 possibilities, I suggest to specify @types/node@8.10.36 as the latest for the node-8.

**Comment by simonlc** [comment]
I think it would be better to leave it as a peer dep so the install isn't done automatically, and a version range. Though after more thought I believe it's best to leave it to the end user using typescript to install them manually. As you said they should probably have it already, and if they don't I imagine the compiler will warn them.

**Comment by muturgan** [comment]
> if they don't I imagine the compiler will warn them.

definitely

**Comment by simonlc** [comment]
Published as async-mkdirp@1.2.7

Thank you 👍

**Comment by muturgan** [comment]
weclome!

**Pull request merged**
